Adding regulations on record upload and key additions.
ivoa-std/StandardsRegExt pull request #2
Opened 2022-12-02 13:07 UTC by msdemlei

2022-12-07 13:59 UTC, rsav requested changes

2022-12-07 13:59 UTC, rsav commented on StandardsRegExt.tex
> +See \url{http://rofr.ivoa.net/} for contact information.
Can we be more specific ? Currently I don't see such a contact information on http://rofr.ivoa.net  other than that that page's support email address (support@canfar.net).

2022-12-07 13:59 UTC, rsav commented on StandardsRegExt.tex
> +       become obsolete.
Can we be stronger here, ie obsoletize vstd:StandardKeyEnumeration in favour of a controled vocabulary ?

2022-12-08 09:36 UTC, msdemlei commented
On Wed, Dec 07, 2022 at 05:59:32AM -0800, Renaud Savalle wrote:
> @rsav requested changes on this pull request.
> +Submission to the ivoa.net registry generally happens through e-mail.
> +See \url{http://rofr.ivoa.net/} for contact information.
> 
> Can we be more specific ? Currently I don't see such a contact
> information on http://rofr.ivoa.net  other than that that page's
> support email address ***@***.***).

Regrettably, this is not specified anywhere.  We could create an
e-Mail address like ***@***.*** for that, but of course that's
another sink for spam.  As long as mail routing is up to the
institution hosting rofr.ivoa.net (and these have been three over the
years already), however, StandardsRegExt can't really say anything
more specific.

So... I guess if we'd like to be more specific here, we should have a
wider discussion on the registry list (and perhaps even include the
TCG).

But then: Perhaps it's already enough if the RofR changes the text on
the web base and says something like

  For support with the Registry of Registries and to submit records
  to it, please contact...

Would that already address your concerns?

> > @@ -404,9 +406,10 @@ \subsection{Summary of Metadata Concepts}
>         standard, it is recommended that the \xmlel{vstd:Standard} or
>         \xmlel{vstd:ServiceStandard} record corresponding to the
>         IVOA standard document be used to define the names.  The
> -       \xmlel{vstd:StandardKeyEnumeration} might be convenient
> -       for definitions that are experimental or otherwise are for
> -       non-IVOA-based applications.  
> +       \xmlel{vstd:StandardKeyEnumeration} was originally envisioned to
> +       as a container for names.  With the adoption of Vocabularies in
> +       the VO 2 \citep{2021ivoa.spec.0525D}, this type has probably
> +       become obsolete.
> 
> Can we be stronger here, ie obsoletize vstd:StandardKeyEnumeration
> in favour of a controled vocabulary ?

Given that ten years after its introduction there still is no
StandardKeyEnumeration in the Registry (see "select distinct res_type
from rr.resource" on any RegTAP mirror), I'd say there is substantial
evidence that there's no particular need addressed by it.  So... I'd
be in on deprecating it entirely.

Suggestion: let's merge this PR and issue an internal WD to the
registry mailing list suggesting a strong deprecation.  If nobody
speaks up against it, we can put it in before we upload the WD.  I've
added a todo to that effect in
8dbf7b9af4a7a9c6b39e87f18f1146f998a3e375.

2023-02-15 14:23 UTC, merged